controllers/PedidosController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Pedidos;
use app\models\Status;
use app\models\Formatos;
use app\models\Tipos;
use app\models\Categorias;
use app\models\Modalidades;
use app\models\Propositos;
use app\models\Paises;
use app\models\Extensiones;
use app\models\Idiomas;
use app\models\Perspectivas;
use app\models\Clientes;
use app\models\PedidosSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PedidosController implements the CRUD actions for Pedidos model.
 */
class PedidosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Pedidos models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PedidosSearch();

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $listStatus=Status::listStatus();
        $listClientes=Clientes::listClientes();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'listStatus' => $listStatus,
            'listClientes' => $listClientes
        ]);
    }

    /**
     * Displays a single Pedidos model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Pedidos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Pedidos();

        $listFormatos=Formatos::listFormatos();
        $listTipos=Tipos::listTipos();
        $listCategorias=Categorias::listCategorias();
        $listModalidades=Modalidades::listModalidades();
        $listPropositos=Propositos::listPropositos();
        $listExtensiones=Extensiones::listExtensiones();
        $listPaises=Paises::listPaises();
        $listIdiomas=Idiomas::listIdiomas();
        $listPerspectivas=Perspectivas::listPerspectivas();
        $listOptimizacion=[1=>'Si',0=>'No'];
        $listClientes=[];

        if(Yii::$app->user->identity->tipoUsuario == 1){
            $listClientes=Clientes::listClientes();
        }else{
            $clienteConectado=Clientes::clienteConectado();
            $model->cliente_id=$clienteConectado['id'];
            $model->cliente_nombre=$clienteConectado['primer_apellido']." ".$clienteConectado['primer_nombre'];
        }


        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $registro=$model->registrarPedido(Yii::$app->request->post());

            if($registro){
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                return $this->redirect(['site/error']);
            }  
        }

        return $this->render('create', [
            'model' => $model,
            'listFormatos' => $listFormatos,
            'listTipos' => $listTipos,
            'listCategorias' => $listCategorias,
            'listModalidades' => $listModalidades,
            'listPropositos' => $listPropositos,
            'listExtensiones' => $listExtensiones,
            'listPaises' => $listPaises,
            'listIdiomas' => $listIdiomas,
            'listOptimizacion' => $listOptimizacion,
            'listClientes' => $listClientes,
            'listPerspectivas' => $listPerspectivas
        ]);
    }

    /**
     * Updates an existing Pedidos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->categorias=$model->categoriasSeleccionadas();
        $model->paises=$model->paisesSeleccionados();

        $listFormatos=Formatos::listFormatos();
        $listTipos=Tipos::listTipos();
        $listCategorias=Categorias::listCategorias();
        $listModalidades=Modalidades::listModalidades();
        $listPropositos=Propositos::listPropositos();
        $listPerspectivas=Perspectivas::listPerspectivas();
        $listExtensiones=Extensiones::listExtensiones();
        $listPaises=Paises::listPaises();
        $listIdiomas=Idiomas::listIdiomas();
        $listOptimizacion=[1=>'Si',0=>'No'];
        $listClientes=[];

        if(Yii::$app->user->identity->tipoUsuario == 1){
            $listClientes=Clientes::listClientes();
        }else{
            $clienteConectado=Clientes::clienteConectado();
            $model->cliente_id=$clienteConectado['id'];
            $model->cliente_nombre=$clienteConectado['primer_apellido']." ".$clienteConectado['primer_nombre'];
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $registro=$model->modificarPedido(Yii::$app->request->post());

            if($registro){
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                return $this->redirect(['site/error']);
            }  
        }


        /*echo "<pre>";
        print_r(Yii::$app->request->post());
        echo "</pre>";
        die;*/

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $registro=$model->modificarPedido(Yii::$app->request->post());

            if($registro){
                return $this->redirect(['view', 'id' => $model->id]);
            }else{
                return $this->redirect(['site/error']);
            }

            
        }

        $model->fecha_entrega=date("d/m/Y",strtotime($model->fecha_entrega));

        return $this->render('update', [
            'model' => $model,
            'listFormatos' => $listFormatos,
            'listTipos' => $listTipos,
            'listCategorias' => $listCategorias,
            'listModalidades' => $listModalidades,
            'listPropositos' => $listPropositos,
            'listPerspectivas' => $listPerspectivas,
            'listExtensiones' => $listExtensiones,
            'listPaises' => $listPaises,
            'listIdiomas' => $listIdiomas,
            'listOptimizacion' => $listOptimizacion,
            'listClientes' => $listClientes
        ]);
    }

    /**
     * Deletes an existing Pedidos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionDeactivate($id){
        $model = $this->findModel($id);
        $model->categorias=1;
        $model->paises=1;
        $model->status_id=2;
        $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
    }

    public function actionActivate($id){
        $model = $this->findModel($id);
        $model->categorias=1;
        $model->paises=1;
        $model->status_id=1;
        $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
    }

    /**
     * Finds the Pedidos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Pedidos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Pedidos::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/pedidos/_botones-acciones.php
<?php
use yii\helpers\Url;
?>
<div class="btn-group  dropleft">
    <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Acciones <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <a href="<?= Url::to(['pedidos/view', 'id' => $model->id]); ?>">
            &nbsp;&nbsp;<span class="ti-search"></span>&nbsp;Consultar</a>
        <a href="<?= Url::to(['pedidos/update', 'id' => $model->id]); ?>">
            &nbsp;&nbsp;<span class="ti-pencil"></span>&nbsp;Modificar</a>
        <?php if($model->status_id == 1){ ?>
            <a href="<?= Url::to(['pedidos/deactivate', 'id' => $model->id]); ?>">
                &nbsp;&nbsp;<span class="ti-close"></span>&nbsp;Desactivar</a>
        <?php } ?>
        <?php if($model->status_id == 2){ ?>
            <a href="<?= Url::to(['pedidos/activate', 'id' => $model->id]); ?>">
                &nbsp;&nbsp;<span class="ti-check"></span>&nbsp;Activar</a>
        <?php } ?>
    </ul>
</div>

views/pedidos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\VarDumper;
use dosamigos\datepicker\DatePicker;
?>

<div class="pedidos-form">

    <?php
    /*echo "<pre>";
    print_r($listPerspectivas);
    echo "</pre>";*/
    ?>

    <?php $form = ActiveForm::begin(['options' => ['enctype'=>'multipart/form-data']]); ?>

    <div class="row formulario">
        <div class="col-md-4 offset-md-2">
            <?= $form->field($model, 'formato_id')->dropDownList($listFormatos,['prompt'=>'SELECCIONE']) ?>
        </div>

        <div class="col-md-4">
            <?= $form->field($model, 'tipo_id')->dropDownList($listTipos,['prompt'=>'SELECCIONE']) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 15px;">
        <div class="col-md-8 offset-md-2">
            <?= $form->field($model, 'categorias')->dropDownList($listCategorias,['class'=>'multipleSelect','multiple'=>'multiple']) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-8 offset-md-2">
            <label class="control-label">Modalidad deseada para tu pedido</label>
                <?=
                $form->field($model, 'modalidad_id')
                    ->radioList(
                        $listModalidades['registros'],
                        [
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<div class="col-md-6">';
                                    $return .= '<div class="caja-modalidad">';
                                        if($checked){
                                            $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" checked="checked">';
                                        }else{
                                            $return .= '<input type="radio" name="' . $name . '" value="' . $value . '">';
                                        }
                                        $return .= '<i></i>';
                                        $return .= ' <span>' . $label['titulo'] . '</span>';
                                        $return .= ' <br><span>' . $label['nombre'] . '</span>';
                                    $return .= '</div>';
                                $return .= '</div>';


                                return $return;
                            }
                        ]
                    )
                ->label(false);
                ?>
        </div>
    </div>

    <div class="row" style="margin-top: 40px;">
        <div class="col-md-8 offset-md-2">
           <?= $form->field($model, 'nombre_proyecto')->textInput(['maxlength' => true]) ?> 
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-8 offset-md-2">
            <label class="control-label">Propósito del texto</label>
            <?=
                $form->field($model, 'proposito_id')
                    ->radioList(
                        $listPropositos['registros'],
                        [
                            'item' => function($index, $label, $name, $checked, $value) {

                                $return = '<div class="col-md-6">';
                                    $return .= '<div class="caja-proposito">';
                                        if($checked){
                                            $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" checked="checked">';
                                        }else{
                                            $return .= '<input type="radio" name="' . $name . '" value="' . $value . '">';
                                        }
                                        $return .= '<i></i>';
                                        $return .= ' <span>' . $label['titulo'] . '</span>';
                                        $return .= ' <br><span>' . $label['nombre'] . '</span>';
                                    $return .= '</div>';
                                $return .= '</div>';


                                return $return;
                            }
                        ]
                    )
                ->label(false);
                ?>
            
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-4 offset-md-2">
            <?= $form->field($model, 'extension_id')->dropDownList($listExtensiones,['prompt'=>'SELECCIONE']) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 45px;">
        <div class="col-md-8 offset-md-2">
            <?= $form->field($model, 'paises')->dropDownList($listPaises,['class'=>'multipleSelect','multiple'=>'multiple']) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-4 offset-md-2">
            <?= $form->field($model, 'idioma_id')->dropDownList($listIdiomas,['prompt'=>'SELECCIONE']) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-4 offset-md-2">
            <?= $form->field($model, 'optimizacion_seo')->dropDownList($listOptimizacion,[]) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-8 offset-md-2">
           <?= $form->field($model, 'palabra_clave')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-8 offset-md-2">
           <?= $form->field($model, 'palabras_secundarias')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-8 offset-md-2">
           <?= $form->field($model, 'descripcion')->textarea(['rows' => 6]) ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-3 offset-md-2">
           <?= Html::button("Adjunta archivo", ['class' => 'form-control btn-file']) ?>
        </div>

        <div class="col-md-3">
           <?= Html::button("Grabar instrucciones", ['class' => 'form-control btn-file']) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-8 offset-md-2">
           <?= $form->field($model, 'publico_objetivo')->textarea(['rows' => 6]) ?>
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-8 offset-md-2">
            <label class="control-label">Perspectiva del texto</label>
            <?=
                $form->field($model, 'perspectiva_id')
                    ->radioList(
                        $listPerspectivas['registros'],
                        [
                            'item' => function($index, $label, $name, $checked, $value) { 
                                $return="";
                                if(!isset($label['padre'])){
                                   $return .="&nbsp;&nbsp;&nbsp;&nbsp;"; 
                                }
                                $disabled="";
                                if(isset($label['padre']) && $label['padre']==1){
                                   $disabled="disabled"; 
                                }
                                if($checked){
                                    $return .= '<input type="radio" name="' . $name . '" value="' . $value . '" checked="checked"'.$disabled.'>';
                                }else{
                                    $return .= '<input type="radio" name="' . $name . '" value="' . $value . '"'.$disabled.'>';
                                }
                                //$return .= '<i></i>';
                                $return .= ' <span>' . $label['nombre'] . '</span><br>';
                                        
                                    


                                return $return;
                            }
                        ]
                    )
                ->label(false);
                ?>
            
        </div>
    </div>

    <div class="row" style="margin-top: 30px;">
        <div class="col-md-4 offset-md-2">
           <?php
           //$form->field($model, 'fecha_entrega')->textInput(['maxlength' => true]) 
           ?>
           <?= $form->field($model, 'fecha_entrega')->widget(
                DatePicker::className(), [
                    // inline too, not bad
                    //'inline' => true,
                    'language' => 'es',
                     // modify template for custom rendering
                    'template' => '{input}{addon}',
                    'options' => ['autocomplete'=>"off",'readonly'=>"readonly"],
                    //'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
                    'clientOptions' => [
                        'autoclose' => true,
                        'format' => 'dd/mm/yyyy'
                    ]
            ]);?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <?php
            if(Yii::$app->user->identity->tipoUsuario == 1){
                echo $form->field($model, 'cliente_id')->dropDownList($listClientes,['prompt'=>'SELECCIONE']);
            }else{
                echo $form->field($model, 'cliente_id')->hiddenInput()->label(false);
                echo $form->field($model, 'cliente_nombre')->textInput();
            }
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <?= Html::submitButton($model->isNewRecord ? 'Crear pedido' : 'Modificar pedido', ['class' => 'btn btn-success pull-right']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pedidos/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PedidosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="pedidos-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'cliente_id') ?>

    <?= $form->field($model, 'formato_id') ?>

    <?= $form->field($model, 'tipo_id') ?>

    <?= $form->field($model, 'modalidad_id') ?>

    <?php // echo $form->field($model, 'nombre_proyecto') ?>

    <?php // echo $form->field($model, 'proposito_id') ?>

    <?php // echo $form->field($model, 'extension_id') ?>

    <?php // echo $form->field($model, 'idioma_id') ?>

    <?php // echo $form->field($model, 'optimizacion_seo') ?>

    <?php // echo $form->field($model, 'palabra_clave') ?>

    <?php // echo $form->field($model, 'palabras_secundarias') ?>

    <?php // echo $form->field($model, 'descripcion') ?>

    <?php // echo $form->field($model, 'archivo') ?>

    <?php // echo $form->field($model, 'grabacion') ?>

    <?php // echo $form->field($model, 'publico_objetivo') ?>

    <?php // echo $form->field($model, 'fecha_entrega') ?>

    <?php // echo $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/pedidos/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pedidos */

$this->title = 'Creación de pedido';
$this->params['breadcrumbs'][] = ['label' => 'Pedidos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pedidos-create">

    <div class="row formulario">
        <div class="col-md-4 offset-md-2">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
        'listFormatos' => $listFormatos,
        'listTipos' => $listTipos,
        'listCategorias' => $listCategorias,
        'listModalidades' => $listModalidades,
        'listPropositos' => $listPropositos,
        'listExtensiones' => $listExtensiones,
        'listPaises' => $listPaises,
        'listIdiomas' => $listIdiomas,
        'listOptimizacion' => $listOptimizacion,
        'listClientes' => $listClientes,
        'listPerspectivas' => $listPerspectivas
    ]) ?>

</div>

<?php
$script="   
    $(document).ready(function(){
        $('#menu-pedidos').addClass('active')
    });
";
$this->registerJs($script);
?>

views/pedidos/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;


$this->title = 'Pedidos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pedidos-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <br>
    <p>
        <?= Html::a('Registrar Pedidos', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?php
    $columnas=[
        ['class' => 'yii\grid\SerialColumn'],
        [
            'attribute'=>'cliente_id',
            'label'=>'Cliente',
            'format'=>"raw",
            'filter'=>Yii::$app->user->identity->tipoUsuario == 1 ? $listClientes : false,
            'value'=>function($objeto,$clave,$index,$widget){
                return $objeto->cliente->apellido_nombre;
                
            },
        ],
        'nombre_proyecto',
        [
            'attribute'=>'fecha_entrega',
            'label'=>'Fecha de entrega',
            'format'=>"raw",
            'filter'=>false,
            'value'=>function($objeto,$clave,$index,$widget){
                return date("d/m/Y",strtotime($objeto->fecha_entrega));
            },
        ],
        [
            'attribute'=>'status_id',
            'label'=>'Estatus',
            'format'=>"raw",
            'filter'=>$listStatus,
            'value'=>function($objeto,$clave,$index,$widget){
                if($objeto->status_id == 1){
                    return "<span class='badge badge-success'>".$objeto->status->nombre."</span>";
                }else{
                    return "<span class='badge badge-danger'>".$objeto->status->nombre."</span>";
                }
                
            },
        ],
        [
            'label'=>'Acciones',
            'format'=>'raw',
            'value'=>function($objeto,$clave,$index,$widget){
                return $objeto->botonesAcciones;
                
            }
        ]
    ];
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => $columnas
    ]); ?>


</div>

<?php
$script="   
    $(document).ready(function(){
        $('#menu-pedidos').addClass('active')
    });
";
$this->registerJs($script);
?>

views/pedidos/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Pedidos */

$this->title = 'Modificación de pedido';
$this->params['breadcrumbs'][] = ['label' => 'Pedidos', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="pedidos-update">

    <div class="row formulario">
        <div class="col-md-4 offset-md-2">
            <h1><?= Html::encode($this->title) ?></h1>
        </div>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
        'listFormatos' => $listFormatos,
        'listTipos' => $listTipos,
        'listCategorias' => $listCategorias,
        'listModalidades' => $listModalidades,
        'listPropositos' => $listPropositos,
        'listPerspectivas' => $listPerspectivas,
        'listExtensiones' => $listExtensiones,
        'listPaises' => $listPaises,
        'listIdiomas' => $listIdiomas,
        'listOptimizacion' => $listOptimizacion,
        'listClientes' => $listClientes
    ]) ?>

</div>

<?php
$script="   
    $(document).ready(function(){
        $('#menu-pedidos').addClass('active')
    });
";
$this->registerJs($script);
?>

views/pedidos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Pedidos */

$this->title = "Consultar pedido";
$this->params['breadcrumbs'][] = ['label' => 'Pedidos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="pedidos-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Listado', ['index'], ['class' => 'btn btn-info']) ?>
        <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php
        if($model->status_id == 1){
            echo Html::a('Desactivar', ['deactivate', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => '¿Seguro que desea desactivar este registro?',
                    'method' => 'post',
                ]
            ]);
        }
        ?>
        
        <?php
        if($model->status_id == 2){
            echo Html::a('Activar', ['activate', 'id' => $model->id], [
                'class' => 'btn btn-success',
                'data' => [
                    'confirm' => '¿Seguro que desea activar este registro?',
                    'method' => 'post',
                ]
            ]);
        }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'label'=>'Cliente',
                'format'=>'raw',
                'value'=>function($objeto){
                    return $objeto->cliente->apellido_nombre;
                    
                }
            ],
            [
                'label'=>'Formato',
                'format'=>'raw',
                'value'=>function($objeto){
                    return $objeto->formato->nombre;
                    
                }
            ],
            [
                'label'=>'Tipo',
                'format'=>'raw',
                'value'=>function($objeto){
                    return $objeto->tipo->nombre;
                    
                }
            ],
            [
                'label'=>'Categorías',
                'format'=>'raw',
                'value'=>function($objeto){
                    $texto="<ul>";
                    foreach ($objeto->pedidosCategorias as  $modelPedidoCategoria) {
                        $texto.="<li>".$modelPedidoCategoria->categoria->nombre."</li>";
                    }
                    $texto.="</ul>";
                    
                    return $texto;
                }
            ],
            [
                'label'=>'Modalidad',
                'format'=>'raw',
                'value'=>function($objeto){
                    $texto="<span><b>".$objeto->modalidad->titulo."</b><span><br>";
                    $texto.="<span>".$objeto->modalidad->nombre."<span><br>";
                    return $texto;
                    
                }
            ],
            'nombre_proyecto',
            [
                'label'=>'Propósito',
                'format'=>'raw',
                'value'=>function($objeto){
                    $texto="<span><b>".$objeto->proposito->titulo."</b><span><br>";
                    $texto.="<span>".$objeto->proposito->nombre."<span><br>";
                    return $texto;
                    
                }
            ],
            [
                'label'=>'Extensión máxima de palabras',
                'format'=>'raw',
                'value'=>function($objeto){
                    return $objeto->extension->nombre;
                    
                }
            ],
            [
                'label'=>'Países a los que está dirigido',
                'format'=>'raw',
                'value'=>function($objeto){
                    $texto="<ul>";
                    foreach ($objeto->pedidosPaises as  $modelPedidoPais) {
                        $texto.="<li>".$modelPedidoPais->pais->nombre."</li>";
                    }
                    $texto.="</ul>";
                    
                    return $texto;
                }
            ],
            [
                'label'=>'Idioma',
                'format'=>'raw',
                'value'=>function($objeto){
                    return $objeto->idioma->nombre;
                    
                }
            ],
            'optimizacion_seo',
            'palabra_clave',
            'palabras_secundarias',
            'descripcion:ntext',
            'publico_objetivo:ntext',
            [
                'label'=>'Perspectiva del texto',
                'format'=>'raw',
                'value'=>function($objeto){
                    $texto="<span>".$objeto->perspectiva->nombre."<span><br>";
                    return $texto;
                    
                }
            ],
            [
                'label'=>'Fecha de entrega',
                'value'=>date("d/m/Y",strtotime($model->fecha_entrega))
            ],
            [
                'label'=>'Estatus',
                'format'=>'raw',
                'value'=>function($objeto){
                    if($objeto->status_id == 1){
                        return "<span class='badge badge-success'>".$objeto->status->nombre."</span>";
                    }else{
                        return "<span class='badge badge-danger'>".$objeto->status->nombre."</span>";
                    }
                }
            ],
            [
                'label'=>'Creado',
                'value'=>date("d/m/Y h:i:s a",strtotime($model->created_at))
            ],
            [
                'label'=>'Modificado',
                'value'=>date("d/m/Y h:i:s a",strtotime($model->updated_at))
            ]
        ],
    ]) ?>

</div>

<?php
$script="   
    $(document).ready(function(){
        $('#menu-pedidos').addClass('active')
    });
";
$this->registerJs($script);
?>