models/Categorias.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

class Categorias extends \yii\db\ActiveRecord{
    
    public static function tableName(){
        return 'categorias';
    }

    
    public function rules(){
        return [
            [['nombre'], 'required','message'=>'Por favor ingrese {attribute}.'],
            [['status_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['nombre'], 'string', 'max' => 100],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => Status::className(), 'targetAttribute' => ['status_id' => 'id']],
        ];
    }

    
    public function attributeLabels(){
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'status_id' => 'Estatus',
            'created_at' => 'Creado',
            'updated_at' => 'Modificado',
        ];
    }

    public function listCategorias(){
        $categorias=Categorias::find()->orderBy(['nombre'=>SORT_ASC])->all();
        $listCategorias=ArrayHelper::map($categorias,'id','nombre');
        return $listCategorias;
    }

    
    public function getStatus(){
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }

    
    public function getPedidosCategorias(){
        return $this->hasMany(PedidosCategorias::className(), ['categoria_id' => 'id']);
    }

    public function getBotonesAcciones(){
        $model=$this;
        return Yii::$app->controller->renderPartial('_botones-acciones',compact('model'));
    }

}

controllers/CategoriasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Categorias;
use app\models\Status;
use app\models\CategoriasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;


class CategoriasController extends Controller{
    
    public function behaviors(){
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    
    public function actionIndex(){
        $searchModel = new CategoriasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $listStatus=Status::listStatus();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'listStatus'=> $listStatus
        ]);
    }

    
    public function actionView($id){
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    
    public function actionCreate(){
        $model = new Categorias();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    
    public function actionUpdate($id){
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    
    public function actionDelete($id){
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    public function actionDeactivate($id){
        $model = $this->findModel($id);
        $model->status_id=2;
        $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
    }

    public function actionActivate($id){
        $model = $this->findModel($id);
        $model->status_id=1;
        $model->save();
        return $this->redirect(['view', 'id' => $model->id]);
    }

    
    protected function findModel($id){
        if (($model = Categorias::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/categorias/_botones-acciones.php
<?php
use yii\helpers\Url;
?>
<div class="btn-group  dropleft">
    <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Acciones <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
        <a href="<?= Url::to(['categorias/view', 'id' => $model->id]); ?>">
            &nbsp;&nbsp;<span class="ti-search"></span>&nbsp;Consultar</a>
        <a href="<?= Url::to(['categorias/update', 'id' => $model->id]); ?>">
            &nbsp;&nbsp;<span class="ti-pencil"></span>&nbsp;Modificar</a>
        <?php if($model->status_id == 1){ ?>
            <a href="<?= Url::to(['categorias/deactivate', 'id' => $model->id]); ?>">
                &nbsp;&nbsp;<span class="ti-close"></span>&nbsp;Desactivar</a>
        <?php } ?>
        <?php if($model->status_id == 2){ ?>
            <a href="<?= Url::to(['categorias/activate', 'id' => $model->id]); ?>">
                &nbsp;&nbsp;<span class="ti-check"></span>&nbsp;Activar</a>
        <?php } ?>
    </ul>
</div>

views/categorias/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<div class="categorias-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Registrar' : 'Modificar', ['class' => 'btn btn-success']) ?>
        <?= Html::a('Listado', ['index'], ['class' => 'btn btn-info']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/categorias/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\CategoriasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="categorias-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'nombre') ?>

    <?= $form->field($model, 'status_id') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/categorias/create.php
<?php

use yii\helpers\Html;


$this->title = 'Registrar Categoría';
//$this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categorias-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/categorias/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;


$this->title = 'Categorías';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categorias-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <br>
    <p>
        <?= Html::a('Registrar Categorías', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'nombre',
            [
                'attribute'=>'status_id',
                'label'=>'Estatus',
                'format'=>"raw",
                'filter'=>$listStatus,
                'value'=>function($objeto,$clave,$index,$widget){
                    if($objeto->status_id == 1){
                        return "<span class='badge badge-success'>".$objeto->status->nombre."</span>";
                    }else{
                        return "<span class='badge badge-danger'>".$objeto->status->nombre."</span>";
                    }
                    
                },
            ],
            [
                'label'=>'Acciones',
                'format'=>'raw',
                'value'=>function($objeto,$clave,$index,$widget){
                    return $objeto->botonesAcciones;
                    
                }
            ],

        ],
    ]); ?>


</div>

views/categorias/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Categorias */

$this->title = 'Modificar Categoría';
$this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="categorias-update">

    <h1><?= Html::encode($this->title) ?></h1>
    <br>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/categorias/view.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;


$this->title = "Consultar categoría";
$this->params['breadcrumbs'][] = ['label' => 'Categorias', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="categorias-view">

    <h1><?= Html::encode($this->title) ?></h1>
    <br>
    <p>
        <?= Html::a('Listado', ['index'], ['class' => 'btn btn-info']) ?>
        <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php
        if($model->status_id == 1){
            echo Html::a('Desactivar', ['deactivate', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => '¿Seguro que desea desactivar este registro?',
                    'method' => 'post',
                ]
            ]);
        }
        ?>
        
        <?php
        if($model->status_id == 2){
            echo Html::a('Activar', ['activate', 'id' => $model->id], [
                'class' => 'btn btn-success',
                'data' => [
                    'confirm' => '¿Seguro que desea activar este registro?',
                    'method' => 'post',
                ]
            ]);
        }
        ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            [
                'label'=>'Estatus',
                'format'=>'raw',
                'value'=>function($objeto){
                    if($objeto->status_id == 1){
                        return "<span class='badge badge-success'>".$objeto->status->nombre."</span>";
                    }else{
                        return "<span class='badge badge-danger'>".$objeto->status->nombre."</span>";
                    }
                }
            ],
            [
                'label'=>'Creado',
                'value'=>date("d/m/Y h:i:s a",strtotime($model->created_at))
            ],
             [
                'label'=>'Modificado',
                'value'=>date("d/m/Y h:i:s a",strtotime($model->updated_at))
            ]
            
        ],
    ]) ?>

</div>